# ДЗ NumPy

<h3>
В этом ноутбуке я собрал несколько достаточно базовых запросов к NumPy. Попробуйте справиться с ними :) 
<br>
К некоторым заданиям прилагаю QR код с подсказкой. 
<br>
Если будет лень искать нужную функцию в документации или интернете, то можете просто считать QR код.<br>
<b>Удачи!</b>
</h3>

<H2>Справка:</H2>

* Коротко про всё необходимое <a href="https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python">здесь</a>;<br>
* Набор шпаргалок (<a href="https://web.itu.edu.tr/iguzel/files/Python_Cheat_Sheets.pdf">тык</a>), рекомендую скачать.

<img src="hints/meme.jpg"/>

### 1. Импортируйте `numpy` с сокращением `np`.

In [1]:
import numpy as np

### 2. Создайте вектор из десяти нулей.

<b>hint</b><br>
<img src="hints/2.png" width=300em/>

In [9]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 3. Определите атрибуты с информацией о весе одного элемента вектора. Определите вес созданного ранее вектора. (Весом буду называют занимаемое в метсо в памяти).

<b>hint</b><br>
<img src="hints/3.png" width=300em/>

In [11]:
arr.itemsize

8

In [12]:
arr.itemsize * arr.size

80

### 4. Создайтек вектор из 10 нулей и замените пятый элемент на единицу.

<b>hint</b><br>
<img src="hints/4.png" width=300em/>

In [13]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 5. Создайте вектор с целыми числами от 10 до 42, включая концы.
<b>hint</b><br>
<img src="hints/5.png" width=300em/>

In [15]:
np.arange(10, 43)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42])

### 6. Создайте вектор с числами от -5 до 5 с шагом 0.25, включая концы.

In [17]:
np.arange(-5, 5.1, 0.25)

array([-5.  , -4.75, -4.5 , -4.25, -4.  , -3.75, -3.5 , -3.25, -3.  ,
       -2.75, -2.5 , -2.25, -2.  , -1.75, -1.5 , -1.25, -1.  , -0.75,
       -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,
        1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ,  3.25,  3.5 ,  3.75,
        4.  ,  4.25,  4.5 ,  4.75,  5.  ])

### 7. Создайте вектор с числами от 0 до 50, не включая 50. "Разверните" его.

<b>hint</b><br>
<img src="hints/7.png" width=300em/>

In [23]:
np.arange(50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### 8. Создайты матрицу из случайных чисел размера 10 на 10.

<b>hint</b><br>
<img src="hints/8.png" width=300em/>

In [27]:
m = (np.random.rand(10, 10) - 0.5) * 1000
m

array([[-439.68828256,  104.71949461, -233.24288952, -108.99190585,
         333.36022181, -109.57723062, -103.72538741,  -14.04698706,
        -497.3144569 ,  335.5854749 ],
       [ 221.44120187,  151.27809501, -168.1430887 ,  199.38022216,
        -238.57282363,   41.49622508,  -61.46460033, -153.97669649,
        -420.68142458,   68.33283165],
       [ -81.29911318, -352.84112246,   53.73615858,  129.13633013,
         279.47576879, -347.61117331, -182.21728849,   47.85491167,
        -449.51798656,  -68.44625499],
       [  81.31874451, -184.82019926,  436.02408708,  172.31625472,
         480.84141161, -419.88744063, -113.12333103,  170.4297528 ,
        -479.12973061,   16.68618724],
       [ 364.34217969, -110.68027023,  136.43780559, -327.48087745,
        -221.14880302, -289.51053457, -406.7202006 ,  383.14437975,
        -475.72251283,  344.73804705],
       [ 123.76110344, -239.2015124 ,  166.45240082,  -43.47222622,
        -329.99202136,  383.90231299, -386.3656138 ,   61

### 9. Определите минимум и максимум матрицы.

<b>hint</b><br>
<img src="hints/9.png" width=300em/>

In [31]:
m.min() == np.min(m)

True

In [32]:
m.max() == np.max(m)

True

### 10. Определите размах (разницу миимума и максимума) за одну строчку кода.

In [34]:
(m.max() - m.min()).round(2)

990.44

In [36]:
np.round(np.max(m) - np.min(m), 2)

990.44

In [38]:
np.sqrt(m) # None

C:\Users\igumn\AppData\Local\Temp\ipykernel_7036\1364206132.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(m)


array([[        nan, 10.23325435,         nan,         nan, 18.25815494,
                nan,         nan,         nan,         nan, 18.31899219],
       [14.88090057, 12.29951605,         nan, 14.12020617,         nan,
         6.44175637,         nan,         nan,         nan,  8.2663675 ],
       [        nan,         nan,  7.33049511, 11.36381671, 16.71752879,
                nan,         nan,  6.91772446,         nan,         nan],
       [ 9.01769064,         nan, 20.88118979, 13.12692861, 21.9280964 ,
                nan,         nan, 13.05487468,         nan,  4.08487298],
       [19.08774947,         nan, 11.68065947,         nan,         nan,
                nan,         nan, 19.57407417,         nan, 18.56712275],
       [11.12479678,         nan, 12.90164334,         nan,         nan,
        19.59342525,         nan,  7.85083957, 22.12506601,         nan],
       [        nan,         nan, 11.73054545,         nan,  7.75175754,
         7.24550986, 17.1753676 , 10.93860396

In [41]:
np.nan # это не None , это другой НаН

nan

### 11. Измените размерность созданной ранее матрицы в вектор-строку.

<b>hint</b><br>
<img src="hints/11.png" width=300em/>

In [42]:
m.shape

(10, 10)

In [43]:
m.reshape(5, 20)

array([[-439.68828256,  104.71949461, -233.24288952, -108.99190585,
         333.36022181, -109.57723062, -103.72538741,  -14.04698706,
        -497.3144569 ,  335.5854749 ,  221.44120187,  151.27809501,
        -168.1430887 ,  199.38022216, -238.57282363,   41.49622508,
         -61.46460033, -153.97669649, -420.68142458,   68.33283165],
       [ -81.29911318, -352.84112246,   53.73615858,  129.13633013,
         279.47576879, -347.61117331, -182.21728849,   47.85491167,
        -449.51798656,  -68.44625499,   81.31874451, -184.82019926,
         436.02408708,  172.31625472,  480.84141161, -419.88744063,
        -113.12333103,  170.4297528 , -479.12973061,   16.68618724],
       [ 364.34217969, -110.68027023,  136.43780559, -327.48087745,
        -221.14880302, -289.51053457, -406.7202006 ,  383.14437975,
        -475.72251283,  344.73804705,  123.76110344, -239.2015124 ,
         166.45240082,  -43.47222622, -329.99202136,  383.90231299,
        -386.3656138 ,   61.63568202,  489.518

In [44]:
m.reshape(50, 2)

array([[-439.68828256,  104.71949461],
       [-233.24288952, -108.99190585],
       [ 333.36022181, -109.57723062],
       [-103.72538741,  -14.04698706],
       [-497.3144569 ,  335.5854749 ],
       [ 221.44120187,  151.27809501],
       [-168.1430887 ,  199.38022216],
       [-238.57282363,   41.49622508],
       [ -61.46460033, -153.97669649],
       [-420.68142458,   68.33283165],
       [ -81.29911318, -352.84112246],
       [  53.73615858,  129.13633013],
       [ 279.47576879, -347.61117331],
       [-182.21728849,   47.85491167],
       [-449.51798656,  -68.44625499],
       [  81.31874451, -184.82019926],
       [ 436.02408708,  172.31625472],
       [ 480.84141161, -419.88744063],
       [-113.12333103,  170.4297528 ],
       [-479.12973061,   16.68618724],
       [ 364.34217969, -110.68027023],
       [ 136.43780559, -327.48087745],
       [-221.14880302, -289.51053457],
       [-406.7202006 ,  383.14437975],
       [-475.72251283,  344.73804705],
       [ 123.76110344, -2

In [49]:
(m.reshape(1, 100) != m.reshape(1, -1)).sum()

0

In [52]:
v = m.reshape(1, -1)
v

array([[-439.68828256,  104.71949461, -233.24288952, -108.99190585,
         333.36022181, -109.57723062, -103.72538741,  -14.04698706,
        -497.3144569 ,  335.5854749 ,  221.44120187,  151.27809501,
        -168.1430887 ,  199.38022216, -238.57282363,   41.49622508,
         -61.46460033, -153.97669649, -420.68142458,   68.33283165,
         -81.29911318, -352.84112246,   53.73615858,  129.13633013,
         279.47576879, -347.61117331, -182.21728849,   47.85491167,
        -449.51798656,  -68.44625499,   81.31874451, -184.82019926,
         436.02408708,  172.31625472,  480.84141161, -419.88744063,
        -113.12333103,  170.4297528 , -479.12973061,   16.68618724,
         364.34217969, -110.68027023,  136.43780559, -327.48087745,
        -221.14880302, -289.51053457, -406.7202006 ,  383.14437975,
        -475.72251283,  344.73804705,  123.76110344, -239.2015124 ,
         166.45240082,  -43.47222622, -329.99202136,  383.90231299,
        -386.3656138 ,   61.63568202,  489.51854

### 12. Определите среднее и стандартное отклонение этого вектора.

<b>hint</b><br>
<img src="hints/12.png" width=300em/>

In [53]:
v.mean()

-17.455574825877623

In [54]:
v.std()

286.4546449331034

### 13. Создайте вектор-стоку из 20 случайных чисел. Прибавьте к нему 5 и умножьте на 10.

In [66]:
x = np.random.rand(20) 

In [67]:
(x + 5) * 10

array([50.68171625, 55.12823437, 59.2163123 , 55.67139489, 54.09652951,
       52.33096355, 55.11973675, 55.74804451, 51.16968945, 57.45005496,
       56.76465261, 52.22975172, 55.44840884, 50.65961474, 55.36124938,
       50.69679168, 50.69623459, 54.70737081, 57.70347469, 57.49863477])

In [68]:
np.multiply(np.add(x, 5), 10)

array([50.68171625, 55.12823437, 59.2163123 , 55.67139489, 54.09652951,
       52.33096355, 55.11973675, 55.74804451, 51.16968945, 57.45005496,
       56.76465261, 52.22975172, 55.44840884, 50.65961474, 55.36124938,
       50.69679168, 50.69623459, 54.70737081, 57.70347469, 57.49863477])

### 14. Для каждого числа вектора определите, сколько процентов от максимального числа составляет это число (напр вектор [1, 4, 8] должен превратиться в [25, 50, 100]).

In [75]:
(x / x.max() * 100).astype(int)

array([  7,  55, 100,  61,  44,  25,  55,  62,  12,  80,  73,  24,  59,
         7,  58,   7,   7,  51,  83,  81])

In [77]:
(x / x.max() * 100).round(1)

array([  7.4,  55.6, 100. ,  61.5,  44.4,  25.3,  55.6,  62.4,  12.7,
        80.8,  73.4,  24.2,  59.1,   7.2,  58.2,   7.6,   7.6,  51.1,
        83.6,  81.4])

### 15. Создайте матрицу с числами из нормального распределение с параметрами: среднее=10, стандартное отклонение=2.5, размерность: 20 на 5.

<b>hint</b><br>
<img src="hints/15.png" width=300em/>

In [80]:
n = np.random.normal(loc=10, scale=2.5, size=100).reshape(20, 5)
n

array([[11.69790584, 11.47714019, 13.44635577,  8.33094967, 12.83562438],
       [10.12832287, 10.97525261, 10.34025011,  6.78905865,  8.331837  ],
       [ 9.64088288,  3.70224272,  8.28501662,  7.73811974,  9.2842085 ],
       [ 8.89201831, 12.08318124,  9.46655391, 15.04758915, 15.47347604],
       [10.3650601 ,  8.95764949,  8.97167457, 12.87110853,  8.06279364],
       [13.54238123, 13.27973959,  9.66358644,  7.07340114,  5.99046466],
       [ 8.23363916, 10.9890578 , 11.04362839,  9.82542246,  7.0517857 ],
       [14.94548672, 10.82131317, 10.15392649,  9.65286073,  7.27988107],
       [10.31808341,  6.9966497 , 11.42229358, 11.59861099, 10.39750837],
       [13.27882494,  9.09711617,  8.02552161, 10.26015024, 10.31526024],
       [ 9.63730973, 13.89256225, 11.62393719,  7.91236142, 10.59579357],
       [11.09900421,  6.26102588, 15.25249423, 12.04809285,  4.33908663],
       [ 8.18407615,  8.20728665,  9.30886281, 11.79567874,  8.29478574],
       [11.73834849, 13.22432529, 10.1

### 16. Центрируйте матрицу. Для этого из каждого столбца надо вычесть среднее значение столбца. Или, если проще, вычесть из матрицы вектор со средними значениями столбцов.

In [91]:
# means = n.mean(axis=0)
means = np.array([10, 20, 30, 40, 50])

In [98]:
n = np.zeros([10, 5])
n

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [99]:
n - means

array([[-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.]])

In [102]:
means = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100]).reshape(-1, 1)

In [104]:
n - means

array([[ -10.,  -10.,  -10.,  -10.,  -10.],
       [ -20.,  -20.,  -20.,  -20.,  -20.],
       [ -30.,  -30.,  -30.,  -30.,  -30.],
       [ -40.,  -40.,  -40.,  -40.,  -40.],
       [ -50.,  -50.,  -50.,  -50.,  -50.],
       [ -60.,  -60.,  -60.,  -60.,  -60.],
       [ -70.,  -70.,  -70.,  -70.,  -70.],
       [ -80.,  -80.,  -80.,  -80.,  -80.],
       [ -90.,  -90.,  -90.,  -90.,  -90.],
       [-100., -100., -100., -100., -100.]])

In [107]:
m = m.reshape(25, 4)
m.shape

(25, 4)

In [110]:
m_centered = m - m.mean(axis=0)

In [111]:
m_centered.mean(axis=0)

array([-1.76214598e-14,  9.09494702e-15,  9.09494702e-15, -1.81898940e-14])

### 17. Стандартизируйте эту матрицу
(т.е. для каждого $x $ нужно провести операцию<br>

$ \large x_{new} = \frac{x_{old} - column_{mean}}{column_{std}}$

In [113]:
(m_centered.std(axis=0) != m.std(axis=0)).sum()

0

In [114]:
m_centered / m_centered.std(axis=0)

array([[-1.27607609,  0.15356955, -0.79824008, -0.17989709],
       [ 1.50866045, -0.67474313, -0.3721347 ,  0.16007447],
       [-1.48366166,  1.04592671,  0.6976453 ,  0.75205796],
       [-0.29789449,  0.51945792, -0.81577526,  0.35895938],
       [ 0.08639121, -0.84635863, -1.41490243,  0.45505386],
       [ 0.01494175, -1.61502145,  0.14590503,  0.67277441],
       [ 1.31455361, -1.59480633, -0.63036869,  0.38172808],
       [-1.31148543, -0.51576119,  0.2366502 , -0.45141728],
       [ 1.87848436,  0.41484864,  1.55105756, -1.2931282 ],
       [-0.09969796,  0.40755682, -1.60719411,  0.27012148],
       [ 1.62026611, -0.67900666,  0.41798885, -0.9622458 ],
       [-0.48883587, -1.37023222, -1.36897078,  1.58230713],
       [-1.40588145,  1.08130379,  0.37628321, -0.64614175],
       [ 0.90741188, -0.41923006, -1.11653934,  1.58502108],
       [-1.08399295, -0.01296061,  1.57960485, -1.21446261],
       [-0.64026006, -1.29256402,  0.42183115, -0.47780373],
       [ 0.5242639 , -0.

In [115]:
# за один шаг
(m - m.mean(axis=0)) / m.std(axis=0)

array([[-1.27607609,  0.15356955, -0.79824008, -0.17989709],
       [ 1.50866045, -0.67474313, -0.3721347 ,  0.16007447],
       [-1.48366166,  1.04592671,  0.6976453 ,  0.75205796],
       [-0.29789449,  0.51945792, -0.81577526,  0.35895938],
       [ 0.08639121, -0.84635863, -1.41490243,  0.45505386],
       [ 0.01494175, -1.61502145,  0.14590503,  0.67277441],
       [ 1.31455361, -1.59480633, -0.63036869,  0.38172808],
       [-1.31148543, -0.51576119,  0.2366502 , -0.45141728],
       [ 1.87848436,  0.41484864,  1.55105756, -1.2931282 ],
       [-0.09969796,  0.40755682, -1.60719411,  0.27012148],
       [ 1.62026611, -0.67900666,  0.41798885, -0.9622458 ],
       [-0.48883587, -1.37023222, -1.36897078,  1.58230713],
       [-1.40588145,  1.08130379,  0.37628321, -0.64614175],
       [ 0.90741188, -0.41923006, -1.11653934,  1.58502108],
       [-1.08399295, -0.01296061,  1.57960485, -1.21446261],
       [-0.64026006, -1.29256402,  0.42183115, -0.47780373],
       [ 0.5242639 , -0.