# ДЗ NumPy

<h3>
В этом ноутбуке я собрал несколько достаточно базовых запросов к NumPy. Попробуйте справиться с ними :) 
<br>
К некоторым заданиям прилагаю QR код с подсказкой. 
<br>
Если будет лень искать нужную функцию в документации или интернете, то можете просто считать QR код.<br>
<b>Удачи!</b>
</h3>

<H2>Справка:</H2>

* Коротко про всё необходимое <a href="https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python">здесь</a>;<br>
* Набор шпаргалок (<a href="https://web.itu.edu.tr/iguzel/files/Python_Cheat_Sheets.pdf">тык</a>), рекомендую скачать.

<img src="hints/meme.jpg"/>

### 1. Импортируйте `numpy` с сокращением `np`.

In [1]:
import numpy as np

### 2. Создайте вектор из десяти нулей.

<b>hint</b><br>
<img src="hints/2.png" width=300em/>

In [9]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 3. Определите атрибуты с информацией о весе одного элемента вектора. Определите вес созданного ранее вектора. (Весом буду называют занимаемое в метсо в памяти).

<b>hint</b><br>
<img src="hints/3.png" width=300em/>

In [11]:
arr.itemsize

8

In [12]:
arr.itemsize * arr.size

80

### 4. Создайте вектор из 10 нулей и замените пятый элемент на единицу.

<b>hint</b><br>
<img src="hints/4.png" width=300em/>

In [13]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 5. Создайте вектор с целыми числами от 10 до 42, включая концы.
<b>hint</b><br>
<img src="hints/5.png" width=300em/>

In [15]:
np.arange(10, 43)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42])

### 6. Создайте вектор с числами от -5 до 5 с шагом 0.25, включая концы.

In [17]:
np.arange(-5, 5.1, 0.25)

array([-5.  , -4.75, -4.5 , -4.25, -4.  , -3.75, -3.5 , -3.25, -3.  ,
       -2.75, -2.5 , -2.25, -2.  , -1.75, -1.5 , -1.25, -1.  , -0.75,
       -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,
        1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ,  3.25,  3.5 ,  3.75,
        4.  ,  4.25,  4.5 ,  4.75,  5.  ])

### 7. Создайте вектор с числами от 0 до 50, не включая 50. "Разверните" его.

<b>hint</b><br>
<img src="hints/7.png" width=300em/>

In [23]:
np.arange(50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### 8. Создайты матрицу из случайных чисел размера 10 на 10.

<b>hint</b><br>
<img src="hints/8.png" width=300em/>

In [22]:
m = (np.random.rand(10, 10) - 0.5) * 1000
m

array([[  -7.56090058, -489.79040898,  -45.90632044,  227.876619  ,
          81.66856734,  -72.72342571, -413.9362164 ,  -37.8834406 ,
        -265.10369295,   38.55390203],
       [ 447.11536747, -376.03726091,  251.4717216 , -388.27750738,
        -439.82523363,  347.58001446,   99.86963106, -295.19162301,
         372.36908533,  303.78950146],
       [ 418.64374422, -472.93037315,  433.82940896,  -89.04011375,
         461.07900255,  450.22549444,  185.99150115, -357.68303742,
          11.73615175,   47.32624773],
       [-388.3842428 ,  460.22892955, -204.3978653 ,  393.57536754,
          32.28775819,   -6.92529848,   39.93365719,  -62.09748905,
        -412.69459357, -260.53207942],
       [-485.84440093, -380.47507783,  491.93926015,  392.12102004,
         105.32792579,  395.06237691, -371.78021353, -127.38294648,
        -237.80480652, -282.94939882],
       [ -80.36032521,  135.05834821, -291.37111486,  286.11819231,
         439.93932764, -113.89256483, -176.40410615, -331

#### Списочные сокращения

In [2]:
nums = ['1', '5', '10', '100']
for i in range(len(nums)):
    nums[i] = int(nums[i])
print(nums)

[1, 5, 10, 100]


In [3]:
nums = [int(i) for i in nums]
print(nums)

[1, 5, 10, 100]


In [4]:
[i ** 2 - 4 for i in nums]

[-3, 21, 96, 9996]

In [5]:
[i**3 for i in nums if i < 100]

[1, 125, 1000]

In [ ]:
from random import random

In [18]:
%%timeit
m = []
for i in range(2500):
    row = []
    for j in range(2500):
        row.append(random())
    m.append(row)

2.64 s ± 652 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
%%timeit
m = [[random() for i in range(2500)] for j in range(2500)]

1.52 s ± 276 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [21]:
%%timeit
m = np.random.rand(2500, 2500)

164 ms ± 36.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 9. Определите минимум и максимум матрицы.

<b>hint</b><br>
<img src="hints/9.png" width=300em/>

In [31]:
m.min() == np.min(m)

True

In [32]:
m.max() == np.max(m)

True

### 10. Определите размах (разницу миимума и максимума) за одну строчку кода.

In [34]:
(m.max() - m.min()).round(2)

990.44

In [36]:
np.round(np.max(m) - np.min(m), 2)

990.44

In [38]:
np.sqrt(m) # None

C:\Users\igumn\AppData\Local\Temp\ipykernel_7036\1364206132.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(m)


array([[        nan, 10.23325435,         nan,         nan, 18.25815494,
                nan,         nan,         nan,         nan, 18.31899219],
       [14.88090057, 12.29951605,         nan, 14.12020617,         nan,
         6.44175637,         nan,         nan,         nan,  8.2663675 ],
       [        nan,         nan,  7.33049511, 11.36381671, 16.71752879,
                nan,         nan,  6.91772446,         nan,         nan],
       [ 9.01769064,         nan, 20.88118979, 13.12692861, 21.9280964 ,
                nan,         nan, 13.05487468,         nan,  4.08487298],
       [19.08774947,         nan, 11.68065947,         nan,         nan,
                nan,         nan, 19.57407417,         nan, 18.56712275],
       [11.12479678,         nan, 12.90164334,         nan,         nan,
        19.59342525,         nan,  7.85083957, 22.12506601,         nan],
       [        nan,         nan, 11.73054545,         nan,  7.75175754,
         7.24550986, 17.1753676 , 10.93860396

In [41]:
np.nan # это не None , это другой НаН

nan

### 11. Измените размерность созданной ранее матрицы в вектор-строку.

<b>hint</b><br>
<img src="hints/11.png" width=300em/>

In [42]:
m.shape

(10, 10)

In [27]:
m.reshape(5, 20)

array([[  -7.56090058, -489.79040898,  -45.90632044,  227.876619  ,
          81.66856734,  -72.72342571, -413.9362164 ,  -37.8834406 ,
        -265.10369295,   38.55390203,  447.11536747, -376.03726091,
         251.4717216 , -388.27750738, -439.82523363,  347.58001446,
          99.86963106, -295.19162301,  372.36908533,  303.78950146],
       [ 418.64374422, -472.93037315,  433.82940896,  -89.04011375,
         461.07900255,  450.22549444,  185.99150115, -357.68303742,
          11.73615175,   47.32624773, -388.3842428 ,  460.22892955,
        -204.3978653 ,  393.57536754,   32.28775819,   -6.92529848,
          39.93365719,  -62.09748905, -412.69459357, -260.53207942],
       [-485.84440093, -380.47507783,  491.93926015,  392.12102004,
         105.32792579,  395.06237691, -371.78021353, -127.38294648,
        -237.80480652, -282.94939882,  -80.36032521,  135.05834821,
        -291.37111486,  286.11819231,  439.93932764, -113.89256483,
        -176.40410615, -331.45027032, -346.840

In [44]:
m.reshape(50, 2)

array([[-439.68828256,  104.71949461],
       [-233.24288952, -108.99190585],
       [ 333.36022181, -109.57723062],
       [-103.72538741,  -14.04698706],
       [-497.3144569 ,  335.5854749 ],
       [ 221.44120187,  151.27809501],
       [-168.1430887 ,  199.38022216],
       [-238.57282363,   41.49622508],
       [ -61.46460033, -153.97669649],
       [-420.68142458,   68.33283165],
       [ -81.29911318, -352.84112246],
       [  53.73615858,  129.13633013],
       [ 279.47576879, -347.61117331],
       [-182.21728849,   47.85491167],
       [-449.51798656,  -68.44625499],
       [  81.31874451, -184.82019926],
       [ 436.02408708,  172.31625472],
       [ 480.84141161, -419.88744063],
       [-113.12333103,  170.4297528 ],
       [-479.12973061,   16.68618724],
       [ 364.34217969, -110.68027023],
       [ 136.43780559, -327.48087745],
       [-221.14880302, -289.51053457],
       [-406.7202006 ,  383.14437975],
       [-475.72251283,  344.73804705],
       [ 123.76110344, -2

In [29]:
(m.reshape(1, 100) != m.reshape(1, -1)).sum()

0

In [52]:
v = m.reshape(1, -1)
v

array([[-439.68828256,  104.71949461, -233.24288952, -108.99190585,
         333.36022181, -109.57723062, -103.72538741,  -14.04698706,
        -497.3144569 ,  335.5854749 ,  221.44120187,  151.27809501,
        -168.1430887 ,  199.38022216, -238.57282363,   41.49622508,
         -61.46460033, -153.97669649, -420.68142458,   68.33283165,
         -81.29911318, -352.84112246,   53.73615858,  129.13633013,
         279.47576879, -347.61117331, -182.21728849,   47.85491167,
        -449.51798656,  -68.44625499,   81.31874451, -184.82019926,
         436.02408708,  172.31625472,  480.84141161, -419.88744063,
        -113.12333103,  170.4297528 , -479.12973061,   16.68618724,
         364.34217969, -110.68027023,  136.43780559, -327.48087745,
        -221.14880302, -289.51053457, -406.7202006 ,  383.14437975,
        -475.72251283,  344.73804705,  123.76110344, -239.2015124 ,
         166.45240082,  -43.47222622, -329.99202136,  383.90231299,
        -386.3656138 ,   61.63568202,  489.51854

### 12. Определите среднее и стандартное отклонение этого вектора.

<b>hint</b><br>
<img src="hints/12.png" width=300em/>

In [53]:
v.mean()

-17.455574825877623

In [54]:
v.std()

286.4546449331034

### 13. Создайте вектор-стоку из 20 случайных чисел. Прибавьте к нему 5 и умножьте на 10.

In [30]:
x = np.random.rand(20) 

In [31]:
(x + 5) * 10

array([54.94818618, 57.61914823, 51.85733517, 52.12951294, 54.98104386,
       52.71396283, 56.85844192, 59.83281262, 54.03741371, 50.47053444,
       51.75453953, 53.49699091, 51.203457  , 55.45381596, 53.36283263,
       53.06814504, 59.72011298, 52.2889373 , 59.15326977, 51.32466445])

In [32]:
np.multiply(np.add(x, 5), 10)

array([54.94818618, 57.61914823, 51.85733517, 52.12951294, 54.98104386,
       52.71396283, 56.85844192, 59.83281262, 54.03741371, 50.47053444,
       51.75453953, 53.49699091, 51.203457  , 55.45381596, 53.36283263,
       53.06814504, 59.72011298, 52.2889373 , 59.15326977, 51.32466445])

### 14. Для каждого числа вектора определите, сколько процентов от максимального числа составляет это число (напр вектор [1, 4, 8] должен превратиться в [25, 50, 100]).

In [35]:
(x / x.max() * 100).astype(int)

array([ 50,  77,  18,  21,  50,  27,  69, 100,  41,   4,  17,  35,  12,
        55,  34,  31,  98,  23,  93,  13])

In [40]:
(x / x.max() * 100).round(1)

array([ 50.3,  77.5,  18.9,  21.7,  50.7,  27.6,  69.8, 100. ,  41.1,
         4.8,  17.8,  35.6,  12.2,  55.5,  34.2,  31.2,  98.9,  23.3,
        93.1,  13.5])

### 15. Создайте матрицу с числами из нормального распределение с параметрами: среднее=10, стандартное отклонение=2.5, размерность: 20 на 5.

<b>hint</b><br>
<img src="hints/15.png" width=300em/>

In [42]:
n = np.random.normal(loc=10, scale=2.5, size=100).reshape(20, 5)
n

array([[ 9.92783086,  8.38240405, 10.96951338,  9.54268385, 12.50996674],
       [ 9.12571126, 14.92010412, 14.0690823 ,  8.92558624, 10.27028033],
       [10.49333392,  9.06952281, 11.51144521, 10.92319808,  7.13342732],
       [ 6.54485862,  8.23372162, 12.6149352 , 11.20479246,  9.75613622],
       [15.83743316,  8.73046885, 11.11930343,  9.8789875 ,  7.815018  ],
       [11.65361439, 12.73183893,  7.44284529,  8.68279271,  9.61538479],
       [12.61785979, 11.44690277, 11.7375524 , 10.92718906,  8.68087911],
       [11.13681088,  9.69542923, 11.44484825,  9.95591757, 11.9248176 ],
       [ 9.74503484,  8.35265421,  7.94048547, 13.1522815 , 12.86406198],
       [ 9.13470907, 12.81297481, 10.25026356, 13.12027769,  9.95110293],
       [ 6.63211332,  7.86053146, 10.38467215, 13.57090823,  6.19112632],
       [ 8.07183203, 12.66327202, 14.09444092, 11.05822163, 13.40575022],
       [ 8.73716354, 12.37227267, 12.03224906,  9.83488759,  9.62700848],
       [ 9.62086436, 10.26886539, 12.2

### 16. Центрируйте матрицу. Для этого из каждого столбца надо вычесть среднее значение столбца. Или, если проще, вычесть из матрицы вектор со средними значениями столбцов.

In [91]:
# means = n.mean(axis=0)
means = np.array([10, 20, 30, 40, 50])

In [98]:
n = np.zeros([10, 5])
n

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [99]:
n - means

array([[-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.]])

In [102]:
means = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100]).reshape(-1, 1)

In [104]:
n - means

array([[ -10.,  -10.,  -10.,  -10.,  -10.],
       [ -20.,  -20.,  -20.,  -20.,  -20.],
       [ -30.,  -30.,  -30.,  -30.,  -30.],
       [ -40.,  -40.,  -40.,  -40.,  -40.],
       [ -50.,  -50.,  -50.,  -50.,  -50.],
       [ -60.,  -60.,  -60.,  -60.,  -60.],
       [ -70.,  -70.,  -70.,  -70.,  -70.],
       [ -80.,  -80.,  -80.,  -80.,  -80.],
       [ -90.,  -90.,  -90.,  -90.,  -90.],
       [-100., -100., -100., -100., -100.]])

In [46]:
n = np.zeros(25).reshape(5, 5)
means = np.arange(10, 51, 10)

In [48]:
n

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
means

array([10, 20, 30, 40, 50])

In [50]:
n - means

array([[-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.],
       [-10., -20., -30., -40., -50.]])

In [55]:
(n - means).T

array([[-10., -10., -10., -10., -10.],
       [-20., -20., -20., -20., -20.],
       [-30., -30., -30., -30., -30.],
       [-40., -40., -40., -40., -40.],
       [-50., -50., -50., -50., -50.]])

In [56]:
m = m.reshape(25, 4)
m.shape

(25, 4)

In [60]:
m.mean(axis=0)

array([ 31.20803991,  14.01608746, -63.45347579,  28.11501071])

In [110]:
m_centered = m - m.mean(axis=0)

In [111]:
m_centered.mean(axis=0)

array([-1.76214598e-14,  9.09494702e-15,  9.09494702e-15, -1.81898940e-14])

### 17. Стандартизируйте эту матрицу
(т.е. для каждого $x $ нужно провести операцию<br>

$ \large x_{new} = \frac{x_{old} - column_{mean}}{column_{std}}$

In [113]:
(m_centered.std(axis=0) != m.std(axis=0)).sum()

0

In [114]:
m_centered / m_centered.std(axis=0)

array([[-1.27607609,  0.15356955, -0.79824008, -0.17989709],
       [ 1.50866045, -0.67474313, -0.3721347 ,  0.16007447],
       [-1.48366166,  1.04592671,  0.6976453 ,  0.75205796],
       [-0.29789449,  0.51945792, -0.81577526,  0.35895938],
       [ 0.08639121, -0.84635863, -1.41490243,  0.45505386],
       [ 0.01494175, -1.61502145,  0.14590503,  0.67277441],
       [ 1.31455361, -1.59480633, -0.63036869,  0.38172808],
       [-1.31148543, -0.51576119,  0.2366502 , -0.45141728],
       [ 1.87848436,  0.41484864,  1.55105756, -1.2931282 ],
       [-0.09969796,  0.40755682, -1.60719411,  0.27012148],
       [ 1.62026611, -0.67900666,  0.41798885, -0.9622458 ],
       [-0.48883587, -1.37023222, -1.36897078,  1.58230713],
       [-1.40588145,  1.08130379,  0.37628321, -0.64614175],
       [ 0.90741188, -0.41923006, -1.11653934,  1.58502108],
       [-1.08399295, -0.01296061,  1.57960485, -1.21446261],
       [-0.64026006, -1.29256402,  0.42183115, -0.47780373],
       [ 0.5242639 , -0.

In [115]:
# за один шаг
(m - m.mean(axis=0)) / m.std(axis=0)

array([[-1.27607609,  0.15356955, -0.79824008, -0.17989709],
       [ 1.50866045, -0.67474313, -0.3721347 ,  0.16007447],
       [-1.48366166,  1.04592671,  0.6976453 ,  0.75205796],
       [-0.29789449,  0.51945792, -0.81577526,  0.35895938],
       [ 0.08639121, -0.84635863, -1.41490243,  0.45505386],
       [ 0.01494175, -1.61502145,  0.14590503,  0.67277441],
       [ 1.31455361, -1.59480633, -0.63036869,  0.38172808],
       [-1.31148543, -0.51576119,  0.2366502 , -0.45141728],
       [ 1.87848436,  0.41484864,  1.55105756, -1.2931282 ],
       [-0.09969796,  0.40755682, -1.60719411,  0.27012148],
       [ 1.62026611, -0.67900666,  0.41798885, -0.9622458 ],
       [-0.48883587, -1.37023222, -1.36897078,  1.58230713],
       [-1.40588145,  1.08130379,  0.37628321, -0.64614175],
       [ 0.90741188, -0.41923006, -1.11653934,  1.58502108],
       [-1.08399295, -0.01296061,  1.57960485, -1.21446261],
       [-0.64026006, -1.29256402,  0.42183115, -0.47780373],
       [ 0.5242639 , -0.