# Сколько времени работает программа?

## cell magick

In [1]:
s = 0
for i in range(1, 1_000_000+1):
    s += i
print(s)

500000500000


In [4]:
%%time
s = 0
for i in range(1, 10_000_000+1):
    s += i
print(s)

50000005000000
CPU times: total: 5.69 s
Wall time: 6.04 s


In [5]:
%%timeit
s = 0
for i in range(1, 10_000_000+1):
    s += i
print(s)

50000005000000
50000005000000
50000005000000
50000005000000
50000005000000
50000005000000
50000005000000
50000005000000
2.05 s ± 365 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
import time

time.time() / 60 / 60 / 24 / 365

53.896933741775634

In [10]:
start = time.time()

s = 0
for i in range(1, 10_000_000+1):
    s += i
print(s)

end = time.time()
print(round(end - start, 2))

50000005000000
6.27


In [12]:
%%timeit
s = 0
for i in range(1000):
    for j in range(1000):
        s += i*j
print(s)

249500250000
249500250000
249500250000
249500250000
249500250000
249500250000
249500250000
249500250000
344 ms ± 44.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [14]:
%%time
s = 0
for i in range(10000):
    for j in range(10000):
        s += i*j
print(s)

2499500025000000
CPU times: total: 1min 12s
Wall time: 1min 16s


In [1]:
import numpy

In [28]:
# %%timeit
numpy.sum(numpy.arange(1, 10_000_000+1),dtype='int64')

50000005000000

In [29]:
50000005000000 / 1e9

50000.005

In [14]:
%%timeit
numpy.sum(numpy.arange(1, 1001) * numpy.arange(1, 1001).reshape(-1, 1))

7.78 ms ± 689 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [15]:
76000 / 8

9500.0

## Numpy Tutorial

### import numpy

In [17]:
import numpy as np

### check python and numpy version

In [18]:
import platform
print('Python version: ' + platform.python_version())
print('Numpy version: ' + np.__version__)

Python version: 3.9.16
Numpy version: 1.24.3


# 0. Numpy Data Types

### A list of Numpy Data Types

In [3]:
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

In [5]:
# create an array with a specified data type
arr = np.array([1,2,3], dtype='f4')
print(arr)
print(arr.dtype)

arr = np.array([1+2j, 3-4j], dtype=np.complex64)
print(arr)
print(arr.dtype)

arr = np.array([0, 1, 1], dtype=np.bool)
print(arr)
print(arr.dtype)

[1. 2. 3.]
float32
[1.+2.j 3.-4.j]
complex64
[False  True  True]
bool


C:\Users\igumn\AppData\Local\Temp\ipykernel_15340\713103193.py:10: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr = np.array([0, 1, 1], dtype=np.bool)


In [175]:
bool(0)

False

In [177]:
0 == False

True

### string data type

In [6]:
# set the max length of the string using S + some number, such as 'S3'
# any string longer than the max length will be truncated
s = np.array(['abc', 'defg'], dtype='S3')
print(s)
print(s.dtype)

[b'abc' b'def']
|S3


In [7]:
# numpy string and unicode data types are fixed-length
# string_ and unicode_ will treat the longest string in the array as the default length when creating an array
arr = np.array(['a', 'ab', 'abc'], dtype=np.string_)
print(arr.dtype)

arr = np.array(['a', 'ab', 'abc'], dtype=np.unicode_)
print(arr.dtype)

|S3
<U3


In [8]:
# what does "|" and "<" mean above?
# they are the byte order indicators, which is beyond the scope of this tutorial
# you can check it out here: https://docs.scipy.org/doc/numpy/reference/generated/numpy.dtype.byteorder.html
# and here: https://en.wikipedia.org/wiki/Endianness

# 1. Create Arrays

### create an array from a Python array

In [6]:
for i in range(3):
    print(i)

0
1
2


In [31]:
arr = np.array(range(10))
print(type(arr))
arr

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


### create an array in a specified data type

In [11]:
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


### create an aray of evenly spaced values within a specified interval

In [3]:
# np.arange(start, stop, step)
arr = np.arange(0, 20, 0.75) 
print(arr)

[ 0.    0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5   8.25
  9.    9.75 10.5  11.25 12.   12.75 13.5  14.25 15.   15.75 16.5  17.25
 18.   18.75 19.5 ]


### create an array of evenly spaced numbers in a specified interval

In [37]:
# np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False) 
arr = np.linspace(0, 10, 21) 
print(arr)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


In [14]:
# exclude endpoint and return setp size
arr, step = np.linspace(0, 10, 20, endpoint=False, retstep=True)
print(arr)
print(step)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
0.5


### create an array of random values in a given shape

In [41]:
arr = np.random.rand(2, 5)
print(arr)

[[0.28657858 0.70179501 0.97212538 0.62582902 0.46658275]
 [0.5902621  0.70867475 0.1020159  0.83018974 0.25841552]]


### create an array of zeros in a given shape 

In [13]:
zeros = np.zeros((2,3), dtype='i4')
print(zeros)

[[0 0 0]
 [0 0 0]]


### create an array of zeros with the same shape and data type as a given array

In [14]:
zeros = np.zeros_like(arr)
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### create an array of ones in a given shape 

In [15]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


### create an array of ones with the same shape and data type as a given array

In [16]:
ones = np.ones_like(arr)
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### create an array of arbitrary values in a given shape 

In [17]:
empty = np.empty((2,3))
print(empty)

[[1. 1. 1.]
 [1. 1. 1.]]


### create an array of arbitrary values with the same shape and data type as a given array

In [21]:
empty = np.empty_like(arr)
print(empty)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### create an array of constant values in a given shape  

In [18]:
p = np.full((2,3), 5)
print(p)

[[5 5 5]
 [5 5 5]]


### create an array of constant values with the same shape and data type as a given array

In [19]:
p = np.full_like(arr, 5)
print(p)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


### create an array by repetition

In [10]:
# repeat each element of an array by a specified number of times
# np.repeat(iterable, reps, axis=None)
arr = [0, 1, 2]
print(np.repeat(arr, 3))    # or np.repeat(range(3), 3)

[0 0 0 1 1 1 2 2 2]


In [21]:
# repeat along a specified axis with specified number of repetitions
arr = [[1,2], [3,4]]
print(np.repeat(arr, [1,2], axis=0))

[[1 2]
 [3 4]
 [3 4]]


In [26]:
# repeat an array by a specified number of times
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [27]:
# repeat along specified axes
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


### create an identity matrix with a given diagonal size

In [28]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### create an identity matrix with a diagonal offset

In [30]:
identity_matrix = np.eye(5, k=1)    # positive number shifts the diagonal upward
print(identity_matrix)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [31]:
identity_matrix = np.eye(5, k=-2)   # negative number shifts the diagonal downward
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


### extract the diagonal array / create a diagonal array

In [23]:
arr = np.random.rand(5,5)
print(arr)

[[0.91841775 0.83930528 0.15055033 0.43768526 0.65227444]
 [0.04613988 0.34907035 0.5716522  0.29587302 0.1424048 ]
 [0.97361535 0.34751267 0.24753934 0.67493789 0.24087317]
 [0.40734278 0.33999048 0.18547185 0.72370042 0.15747436]
 [0.73495302 0.93747283 0.29731374 0.46320829 0.36889643]]


In [24]:
# extract the diagonal
print(np.diag(arr))

[0.91841775 0.34907035 0.24753934 0.72370042 0.36889643]


In [25]:
# create a matrix with a specified diagonal array
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 2. Inspect Arrays

In [26]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)

### inspect general information of an array

In [27]:
print(np.info(arr))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x16b0bf219f0
byteorder:  little
byteswap:  False
type: int64
None


### inspect the data type of an array

In [37]:
print(arr.dtype)

int64


### inspect the dimension of an array

In [38]:
print(arr.shape)

(2, 3)


### inspect length of an array

In [39]:
print(len(arr))

2


### inspect the number of dimensions of an array

In [40]:
print(arr.ndim)

2


### inspect the number of elements in an array

In [41]:
print(arr.size)

6


### inspect the number of bytes of each element in an array

In [42]:
print(arr.itemsize)

8


### inspect the memory size of an array (in byte)

In [43]:
# arr.nbytes = arr.size * arr.itemsize
print(arr.nbytes)

48


# 3. Sampling Methods

### set seed

In [44]:
np.random.seed(123)

### set random state which is independent from the global seed

In [45]:
rs = np.random.RandomState(321)
rs.rand(10)

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])

### generate a random sample from interval [0, 1) in a given shape

In [46]:
# generate a random scalar
print(np.random.rand())      

0.6964691855978616


In [47]:
# generate a 1-D array
print(np.random.rand(3))           

[0.28613933 0.22685145 0.55131477]


In [48]:
# generate a 2-D array
print(np.random.rand(3,3))          

[[0.71946897 0.42310646 0.9807642 ]
 [0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224]]


### generate a sample from the standard normal distribution (mean = 0, var = 1)

In [49]:
print(np.random.randn(3,3))

[[-0.14337247 -0.6191909  -0.76943347]
 [ 0.57674602  0.12652592 -1.30148897]
 [ 2.20742744  0.52274247  0.46564476]]


### generate an array of random integers in a given interval [low, high)

In [50]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[5 7 2]


### generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [51]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.65472131 0.37380143 0.23451288 0.98799529 0.76599595 0.77700444
 0.02798196 0.17390652 0.15408224 0.07708648]
[0.8898657  0.7503787  0.69340324 0.51176338 0.46426806 0.56843069
 0.30254945 0.49730879 0.68326291 0.91669867]
[0.10892895 0.49549179 0.23283593 0.43686066 0.75154299 0.48089213
 0.79772841 0.28270293 0.43341824 0.00975735]
[0.34079598 0.68927201 0.86936929 0.26780382 0.45674792 0.26828131
 0.8370528  0.27051466 0.53006201 0.17537266]


### generate a random sample from a given 1-D array

In [186]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice([0, 1, 2], 10, replace=True, p=[0.15, 0.7, 0.15]))

[1 1 0 1 1 1 1 1 2 2]


In [43]:
print(np.random.choice(3, 10))

[1 2 0 2 2 0 0 1 0 2]


In [54]:
print(np.random.choice([1,2,3], 10))

[2 2 1 3 2 3 1 2 1 3]


### shuffle an array in place

In [55]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [56]:
np.random.shuffle(arr)
print(arr)

[1 2 8 5 4 0 6 7 9 3]


### generate a permutation of an array

In [57]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [3 6 2 4 5 9 1 8 0 7]


# 4. Math Functions

In [11]:
arr = np.random.rand(3,5)
arr

array([[0.02281259, 0.18195302, 0.94276133, 0.12161114, 0.07185866],
       [0.40008854, 0.95168298, 0.32549892, 0.15970933, 0.58717603],
       [0.57836054, 0.65886604, 0.64201957, 0.66480696, 0.01244875]])

In [28]:
x = [1, 2, 3, 4, 5] 
for i in range(len(x)):
    x[i] *= 5
print(x)

[5, 10, 15, 20, 25]


### element-wise addition, subtraction, multiplication and division

In [47]:
arr = arr.round(2)
arr

array([[0.29, 0.7 , 0.97, 0.63, 0.47],
       [0.59, 0.71, 0.1 , 0.83, 0.26]])

In [48]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[10.29 10.7  10.97 10.63 10.47]
 [10.59 10.71 10.1  10.83 10.26]]
[[-9.71 -9.3  -9.03 -9.37 -9.53]
 [-9.41 -9.29 -9.9  -9.17 -9.74]]
[[2.9 7.  9.7 6.3 4.7]
 [5.9 7.1 1.  8.3 2.6]]
[[0.029 0.07  0.097 0.063 0.047]
 [0.059 0.071 0.01  0.083 0.026]]


In [31]:
arr1 = np.array([1,2,3])
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memoryarr = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[1 2 3]
[1 4 9]


### element-wise exponentiation

$ \log_3 27 = ? $

$ 2 ^ x = 5 $ 

$ x = log_2 (5) $ 

$ 2 ^ {\log_2 5} = 5 $ 

In [49]:
print(np.sqrt(arr))

[[0.53851648 0.83666003 0.98488578 0.79372539 0.68556546]
 [0.76811457 0.84261498 0.31622777 0.91104336 0.50990195]]


### element-wise logorithm

In [50]:
# natural log
print(np.log(arr))   

[[-1.23787436 -0.35667494 -0.03045921 -0.46203546 -0.75502258]
 [-0.52763274 -0.34249031 -2.30258509 -0.18632958 -1.34707365]]


In [40]:
# base 2
print(np.log2(arr))     

[[-0.02094348 -0.43154726 -2.61543264 -1.85178487 -0.49856276]
 [-1.19958074 -2.7537137  -6.22571806 -0.07071147 -2.4112762 ]
 [-1.76989074 -0.71607715 -0.09307978 -1.91940796 -2.42921294]]


In [41]:
# base 10
print(np.log10(arr))    

[[-0.00630462 -0.12990867 -0.78732368 -0.55744279 -0.15008235]
 [-0.36110979 -0.82895042 -1.87412788 -0.02128627 -0.72586646]
 [-0.5327902  -0.2155607  -0.02801981 -0.57779937 -0.73126596]]


### element-wise square root

In [42]:
print(np.sqrt(arr))

[[0.99276782 0.86108429 0.40395981 0.52635482 0.84131538]
 [0.65984983 0.38505679 0.1155942  0.97579112 0.43357753]
 [0.54150803 0.78022462 0.96825578 0.5141624  0.4308906 ]]


### element-wise sine and cosine

In [43]:
print(np.sin(arr))

[[0.833597   0.67536989 0.16246026 0.27351876 0.65017259]
 [0.42177474 0.14772608 0.01336162 0.81467486 0.18688417]
 [0.28904676 0.57184283 0.8060925  0.26129443 0.18460182]]


In [44]:
print(np.cos(arr))

[[0.5523731  0.73747916 0.98671509 0.96186667 0.75978656]
 [0.90670065 0.98902831 0.99991073 0.57991798 0.98238196]
 [0.95731498 0.8203632  0.59178956 0.96525915 0.98281339]]


### sum along a specified axis

In [52]:
arr = np.random.rand(3, 5).round(1)
arr

array([[0.1, 0.4, 0.1, 0. , 0.9],
       [0.8, 0.5, 0.4, 0.3, 0.5],
       [0.7, 0.2, 1. , 0.3, 0.9]])

In [53]:
arr.shape

(3, 5)

In [54]:
# sum along the row
print(np.sum(arr, axis=0))  

[1.6 1.1 1.5 0.6 2.3]


In [56]:
# sum along the column
print(np.sum(arr, axis=1))

[1.5 2.5 3.1]


In [58]:
0.1 + 0.1 + 0.1

0.30000000000000004

In [57]:
np.sum(arr)

7.1000000000000005

In [59]:
arr.sum(axis=0)

array([1.6, 1.1, 1.5, 0.6, 2.3])

### compute the min and max along a specified axis

In [60]:
# calculate min along the row
print(np.min(arr, axis=0))

[0.1 0.2 0.1 0.  0.5]


In [61]:
# calculate max along the column
print(np.max(arr, axis=1))    

[0.9 0.8 1. ]


In [62]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

1.0
0.0


### compute the indices of the min and max along a specified axis

In [63]:
# along the row
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))

[0 2 0 0 1]
[1 1 2 1 0]


In [57]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[0 3 0]
[2 4 4]


In [58]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

8
14


### compute element-wise min and max of two arrays

In [76]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


### split fractional and integral parts of a floating-point array

In [66]:
arr1 = np.random.rand(5) * 10
re, intg = np.modf(arr1)
print(arr1)
print('fractional: ', re)
print('integral: ', intg)

[2.29073362 9.07452223 9.78623687 6.8068067  6.78837638]
fractional:  [0.29073362 0.07452223 0.78623687 0.8068067  0.78837638]
integral:  [2. 9. 9. 6. 6.]


### compute the mean

In [68]:
arr

array([[0.36042834, 0.89652253, 0.96100992, 0.47465839, 0.59096585],
       [0.21403449, 0.15385262, 0.10204401, 0.05688106, 0.85855193],
       [0.27736295, 0.35632503, 0.518251  , 0.58482265, 0.9878013 ]])

In [69]:
# compute the overall mean
print(np.mean(arr).round(2))

0.49


In [70]:
# compute the mean along the row
print(np.mean(arr, axis=0))   

[0.28394192 0.46890006 0.52710164 0.3721207  0.8124397 ]


In [71]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

[0.65671701 0.27707282 0.54491258]


### compute the median

In [72]:
# compute the overall median
print(np.median(arr))

0.4746583907644375


In [73]:
# compute the median along the row
print(np.median(arr, axis=0)) 

[0.27736295 0.35632503 0.518251   0.47465839 0.85855193]


In [74]:
# compute the median along the column
print(np.median(arr, axis=1))

[0.59096585 0.15385262 0.518251  ]


### compute the percentile

In [75]:
arr1 = np.random.rand(100)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 65, 95]))

[0.06464754 0.63364606 0.97142615]


### compute the standard deviation & variance

In [76]:
# compute the overall standard deviation
print(np.std(arr))

0.30528309328651343


In [77]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[0.05994582 0.3134693  0.3507272  0.22739989 0.16525606]


In [78]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[0.23467271 0.29543003 0.24722546]


In [79]:
# compute the overall variance
print(np.var(arr))

0.09319776704658204


In [81]:
# compute the variance along the row
print(np.var(arr, axis=0))

[0.0035935  0.098263   0.12300957 0.05171071 0.02730956]


In [82]:
# compute the variance along the column
print(np.var(arr, axis=1))

[0.05507128 0.0872789  0.06112043]


### compute the covariance & correlation

In [83]:
arr = np.random.rand(5,8)

In [84]:
print(np.cov(arr))

[[ 0.07390437  0.05282728  0.00036094 -0.03130674  0.05836293]
 [ 0.05282728  0.11932225 -0.01661794  0.002212    0.03943169]
 [ 0.00036094 -0.01661794  0.02500566 -0.00096847  0.01475511]
 [-0.03130674  0.002212   -0.00096847  0.08074794  0.01819964]
 [ 0.05836293  0.03943169  0.01475511  0.01819964  0.08704155]]


In [85]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[ 1.         -0.22713095]
 [-0.22713095  1.        ]]


### compute cumulative sum & product

In [64]:
arr = (np.random.rand(3, 5) * 10).round(2)
arr

array([[1.02, 8.78, 4.58, 2.82, 8.4 ],
       [5.56, 7.9 , 0.77, 2.06, 3.91],
       [3.08, 0.05, 8.77, 0.73, 0.99]])

In [65]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))    

[[ 1.02  8.78  4.58  2.82  8.4 ]
 [ 6.58 16.68  5.35  4.88 12.31]
 [ 9.66 16.73 14.12  5.61 13.3 ]]


In [91]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1))  

[[ 5.46  5.91 14.1  15.45 16.72]
 [ 1.54  6.51 15.6  16.12 20.61]
 [ 2.22  9.8  18.9  21.05 21.17]]


In [66]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))

[[ 1.02      8.78      4.58      2.82      8.4     ]
 [ 5.6712   69.362     3.5266    5.8092   32.844   ]
 [17.467296  3.4681   30.928282  4.240716 32.51556 ]]


In [94]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))  

[[  5.46         2.457       20.12283     27.1658205   34.50059203]
 [  1.54         7.6538      69.573042    36.17798184 162.43913846]
 [  2.22        16.8276     153.13116    329.231994    39.50783928]]


### element-wise comparison

In [69]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [71]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < arr2)

[False False  True False False]
[ True  True False False False]


# 5. Slicing & Indexing

In [85]:
arr = np.arange(100).reshape((20, 5))
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


### select an element by row and column indices

In [90]:
arr[2][3]

13

In [100]:
print(arr[4][2])
# or more concisely
print(arr[4, 2])

22
22


### indexing with slicing

In [101]:
print(arr[5:10, 2:4])

[[27 28]
 [32 33]
 [37 38]
 [42 43]
 [47 48]]


In [102]:
print(arr[:10, 2:])

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]
 [27 28 29]
 [32 33 34]
 [37 38 39]
 [42 43 44]
 [47 48 49]]


In [105]:
print(arr[:10])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [103]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)
# equivalent to arr[0,:,:,:]
print(arr[0, ...])    

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### assign a scalar to a slice by broadcasting

In [106]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [109]:
arr[5:11, :] = 100    # or simply arr[1:3]
arr[6:10, [1,3]] = -5
print(arr)

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [100 100 100 100 100]
 [100  -5 100  -5 100]
 [100  -5 100  -5 100]
 [100  -5 100  -5 100]
 [100  -5 100  -5 100]
 [100 100 100 100 100]
 [ 55  56  57  58  59]
 [ 60  61  62  63  64]
 [ 65  66  67  68  69]
 [ 70  71  72  73  74]
 [ 75  76  77  78  79]
 [ 80  81  82  83  84]
 [ 85  86  87  88  89]
 [ 90  91  92  93  94]
 [ 95  96  97  98  99]]


### boolean indexing

In [91]:
arr1 = np.arange(25).reshape((5,5))
print(arr1)
print()
bools = np.array([True, True, False, True, False])
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [97]:
arr = np.arange(5, 12,2)
arr

array([ 5,  7,  9, 11])

In [99]:
mask = [True, True, False, False]
arr[mask]

array([5, 7])

In [107]:
arr = np.arange(8).reshape(4, -1)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [108]:
mask = [True, False, True, False]
arr[mask]

array([[0, 1],
       [4, 5]])

In [113]:
mask = [
    [True, False], 
    [True, False], 
    [False, True], 
    [True, False]
]
arr[mask]

array([0, 2, 5, 6])

In [116]:
# negate the condition
print(arr[~mask])    

TypeError: bad operand type for unary ~: 'list'

In [117]:
print(mask)
mask = np.array(mask)
print(mask)

[[True, False], [True, False], [False, True], [True, False]]
[[ True False]
 [ True False]
 [False  True]
 [ True False]]


In [118]:
# negate the condition
print(arr[~mask])

[1 3 4 7]


In [114]:
arr2 = np.array([1,2,3,4,5])
mask = arr2 > 2.5
arr2[mask]

array([3, 4, 5])

In [43]:
arr2[arr2 > 2]

array([3, 4, 5])

In [122]:
mask = arr > 20

In [123]:
arr[mask]

array([ 21,  22,  23,  24, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
        81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99])

In [120]:
arr = np.random.rand(6, 6).round(2)
arr

array([[0.18, 0.12, 0.89, 0.33, 0.31, 0.23],
       [0.23, 0.89, 0.98, 0.9 , 0.3 , 0.64],
       [0.15, 0.03, 0.66, 0.52, 0.02, 0.34],
       [0.08, 0.82, 0.14, 0.85, 0.77, 0.18],
       [0.99, 0.47, 0.68, 0.17, 0.47, 0.59],
       [0.63, 0.6 , 0.19, 0.49, 0.05, 0.49]])

In [121]:
arr[arr > 0.5]

array([0.89, 0.89, 0.98, 0.9 , 0.64, 0.66, 0.52, 0.82, 0.85, 0.77, 0.99,
       0.68, 0.59, 0.63, 0.6 ])

In [124]:
arr2 = np.array([1,2,3,4,5])
arr2 < 2

array([ True, False, False, False, False])

In [125]:
arr2>4

array([False, False, False, False,  True])

In [126]:
a = arr2 < 2
b = arr2 > 2

In [127]:
a & b

array([False, False, False, False, False])

In [128]:
a | b

array([ True, False,  True,  True,  True])

In [122]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions
arr2[(arr2 < 2) | (arr2>4)]
# table[(table.price > 100) & (table.day == 'Monday')]

array([1, 5])

In [135]:
arr = np.random.normal(100_000, 100_000, (1000, 5)).round(1)
arr

array([[ 160924.6,  307214.5,    2581.8,  245022.9,   51461.4],
       [ 105053.2,  128054.5,  180836. ,   35439.7,    8603. ],
       [  22688.1,  155545.1,  -27063.5,    2865.8, -125176.5],
       ...,
       [  66422.4,   85085.9,  149634.8,  186435.4,   91318. ],
       [ 244726. ,   23876.7,  153777.2,  312278.5,   61439.8],
       [   5797.8,  110048. ,  111021.1,  235665.2,  102935. ]])

In [136]:
np.log(arr)

C:\Users\igumn\AppData\Local\Temp\ipykernel_15212\3120950136.py:1: RuntimeWarning: invalid value encountered in log
  np.log(arr)


array([[11.98869121, 12.63530148,  7.85624211, 12.40910695, 10.84858729],
       [11.56222217, 11.76021123, 12.10534582, 10.47558794,  9.05986626],
       [10.02959584, 11.954691  ,         nan,  7.96060282,         nan],
       ...,
       [11.10378963, 11.35141661, 11.91595294, 12.13584008, 11.4221032 ],
       [12.4078945 , 10.08065837, 11.94326008, 12.6516507 , 11.02581311],
       [ 8.66523381, 11.60867191, 11.61747555, 12.37016743, 11.541853  ]])

In [137]:
(arr <= 0).sum(axis=0)

array([143, 173, 154, 159, 145])

In [138]:
np.where(arr <= 0, 1, arr)[1]

array([105053.2, 128054.5, 180836. ,  35439.7,   8603. ])

In [139]:
arr = np.where(arr <= 0, 1, arr)
(arr <= 0).sum(axis=0)

array([0, 0, 0, 0, 0])

In [140]:
np.log(arr)

array([[11.98869121, 12.63530148,  7.85624211, 12.40910695, 10.84858729],
       [11.56222217, 11.76021123, 12.10534582, 10.47558794,  9.05986626],
       [10.02959584, 11.954691  ,  0.        ,  7.96060282,  0.        ],
       ...,
       [11.10378963, 11.35141661, 11.91595294, 12.13584008, 11.4221032 ],
       [12.4078945 , 10.08065837, 11.94326008, 12.6516507 , 11.02581311],
       [ 8.66523381, 11.60867191, 11.61747555, 12.37016743, 11.541853  ]])

In [141]:
arr[arr <= 0] = 1

# ДАЛЬШЕ МОЖНО НЕ СМОТРЕТЬ!

### fancy indexing

In [130]:
arr = np.random.rand(5,5)
arr

array([[0.11821079, 0.84686916, 0.10151737, 0.16528574, 0.45293353],
       [0.28620275, 0.26968018, 0.69053645, 0.9551463 , 0.66920727],
       [0.94708773, 0.00297579, 0.59908326, 0.29807891, 0.80129692],
       [0.34222518, 0.82471484, 0.25191596, 0.16376116, 0.24157371],
       [0.38087217, 0.64184403, 0.68442071, 0.91882332, 0.19060851]])

In [131]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])       

[0.16376116 0.69053645 0.00297579]


In [135]:
# select rows 3,1,2 and columns 6,4,8 
print(arr[[3,1,2]][:, [2,4]])    

[[0.25191596 0.24157371]
 [0.69053645 0.66920727]
 [0.59908326 0.80129692]]


In [136]:
res = arr[[3,1,2]]
res

array([[0.34222518, 0.82471484, 0.25191596, 0.16376116, 0.24157371],
       [0.28620275, 0.26968018, 0.69053645, 0.9551463 , 0.66920727],
       [0.94708773, 0.00297579, 0.59908326, 0.29807891, 0.80129692]])

In [137]:
res = res[:, [2,4]]
res

array([[0.25191596, 0.24157371],
       [0.69053645, 0.66920727],
       [0.59908326, 0.80129692]])

### dimension inference

In [111]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)).reshape((4,-1))
print(arr.shape)

(4, 4)


### find elements/indices by conditions

In [138]:
arr = np.arange(16).reshape(4,4)

In [139]:
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [144]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr > 5, -1, 10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [145]:
print(np.where(arr > 10, 0, arr))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10  0]
 [ 0  0  0  0]]


In [146]:
arr > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [147]:
# find the indices of the elements on conditions
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]


# 6. Sort an Array

In [116]:
arr = np.random.rand(5,5)

### sort an array along a specified axis

In [117]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))   

[[0.11702945 0.17913374 0.06753657 0.02945699 0.05396756]
 [0.13630925 0.18249983 0.41165849 0.12910116 0.31981183]
 [0.36056504 0.51866089 0.42053876 0.56232065 0.37163583]
 [0.44498496 0.62847058 0.42945962 0.70682921 0.43148605]
 [0.7740198  0.74238635 0.55147061 0.86890785 0.75572196]]


In [118]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[0.11702945 0.17913374 0.06753657 0.02945699 0.05396756]
 [0.13630925 0.18249983 0.41165849 0.12910116 0.31981183]
 [0.36056504 0.51866089 0.42053876 0.56232065 0.37163583]
 [0.44498496 0.62847058 0.42945962 0.70682921 0.43148605]
 [0.7740198  0.74238635 0.55147061 0.86890785 0.75572196]]


In [119]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[0.02945699 0.05396756 0.06753657 0.11702945 0.17913374]
 [0.12910116 0.13630925 0.18249983 0.31981183 0.41165849]
 [0.36056504 0.37163583 0.42053876 0.51866089 0.56232065]
 [0.42945962 0.43148605 0.44498496 0.62847058 0.70682921]
 [0.55147061 0.74238635 0.75572196 0.7740198  0.86890785]]


In [120]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

[[0.02945699 0.05396756 0.06753657 0.11702945 0.17913374]
 [0.12910116 0.13630925 0.18249983 0.31981183 0.41165849]
 [0.36056504 0.37163583 0.42053876 0.51866089 0.56232065]
 [0.42945962 0.43148605 0.44498496 0.62847058 0.70682921]
 [0.55147061 0.74238635 0.75572196 0.7740198  0.86890785]]


### compute the indices that would sort an array along a specified axis

In [121]:
arr = np.random.rand(5,5)

In [122]:
# along the row
print(np.argsort(arr, axis=0))

[[1 0 0 4 3]
 [3 2 2 1 0]
 [4 4 3 0 1]
 [2 1 1 2 4]
 [0 3 4 3 2]]


In [123]:
# along the column
print(np.argsort(arr, axis=1))

[[1 2 4 3 0]
 [0 3 1 4 2]
 [1 2 0 3 4]
 [0 4 2 1 3]
 [3 0 1 4 2]]


In [124]:
# if axis=None, return the indices of a flattened array
print(np.argsort(arr, axis=None))

[ 5 23  1 15  2 20 19 11  8 12 17  4  3 21  6  9 24 10 16 13 14  7 22 18
  0]


In [125]:
arr = np.random.rand(3,4)

# 7. Manipulate an Array

### transpose an array

In [126]:
# the following methods return a copy
print(arr.T)
# or 
print(np.transpose(arr))
# or
print(arr.transpose())

[[0.80614361 0.61240133 0.73322903]
 [0.86728799 0.65205696 0.13585084]
 [0.08910079 0.05760322 0.56708195]
 [0.67553447 0.38582245 0.02315444]]
[[0.80614361 0.61240133 0.73322903]
 [0.86728799 0.65205696 0.13585084]
 [0.08910079 0.05760322 0.56708195]
 [0.67553447 0.38582245 0.02315444]]
[[0.80614361 0.61240133 0.73322903]
 [0.86728799 0.65205696 0.13585084]
 [0.08910079 0.05760322 0.56708195]
 [0.67553447 0.38582245 0.02315444]]


### transpose of a high dimensional array with specified order of axes

In [127]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)

arr1.transpose((1,0,2))
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


### swap axes

In [128]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


### change the shape of an array

In [129]:
# change the shape of an array and return a copy
arr.reshape((2,6))

array([[0.80614361, 0.86728799, 0.08910079, 0.67553447, 0.61240133,
        0.65205696],
       [0.05760322, 0.38582245, 0.73322903, 0.13585084, 0.56708195,
        0.02315444]])

In [130]:
# change the shape of an array in place
arr.resize((2,6))

### flatten an array

In [131]:
# return a copy
arr.flatten()    

array([0.80614361, 0.86728799, 0.08910079, 0.67553447, 0.61240133,
       0.65205696, 0.05760322, 0.38582245, 0.73322903, 0.13585084,
       0.56708195, 0.02315444])

In [132]:
# return a view
# change any element in the view will change the initial array
arr.ravel()      

array([0.80614361, 0.86728799, 0.08910079, 0.67553447, 0.61240133,
       0.65205696, 0.05760322, 0.38582245, 0.73322903, 0.13585084,
       0.56708195, 0.02315444])

### append elements to an array

In [133]:
arr = np.array([1,2,3])

In [134]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [135]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


### insert elements into an array

In [136]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [137]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [1,2,3])    
print(arr3)

[1 2 3 1 2 3]


### delete elements from an array

In [138]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [139]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


### copy an array

In [140]:
arr = np.array([1,2,3])

In [141]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
arr1 = arr.copy()
# or 
arr1 = np.array(arr, copy=True)

# ДОПОЛНИТЕЛЬНО

# 8. Combine & Split an Array

In [148]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [149]:
arr2

array([[5, 6, 7, 8],
       [5, 6, 7, 8]])

### ```np.concatenate((a, b), axis=0)```

In [143]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [144]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ```np.vstack((a, b))``` 
### ```np.r_[a, b]```

In [150]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [151]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### ```np.hstack((a, b))```
### ```np.c_[a, b]```

In [152]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [153]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### split an array 

In [149]:
arr = np.random.rand(6,6)

In [150]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[0.0174567 , 0.47275939, 0.84410265, 0.88709809, 0.30063103,
        0.938766  ],
       [0.58832418, 0.09871477, 0.09634253, 0.56561105, 0.75673868,
        0.13910753],
       [0.37247418, 0.98843246, 0.90281137, 0.35097407, 0.48843214,
        0.60597433]]), array([[0.00713459, 0.06267544, 0.65672272, 0.15912001, 0.91006063,
        0.3950984 ],
       [0.46940726, 0.60966449, 0.82131635, 0.48112601, 0.24688737,
        0.40234706],
       [0.20452672, 0.77063506, 0.11895435, 0.98447605, 0.25656521,
        0.39604327]])]


In [151]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.0174567 , 0.47275939, 0.84410265],
       [0.58832418, 0.09871477, 0.09634253],
       [0.37247418, 0.98843246, 0.90281137],
       [0.00713459, 0.06267544, 0.65672272],
       [0.46940726, 0.60966449, 0.82131635],
       [0.20452672, 0.77063506, 0.11895435]]), array([[0.88709809, 0.30063103, 0.938766  ],
       [0.56561105, 0.75673868, 0.13910753],
       [0.35097407, 0.48843214, 0.60597433],
       [0.15912001, 0.91006063, 0.3950984 ],
       [0.48112601, 0.24688737, 0.40234706],
       [0.98447605, 0.25656521, 0.39604327]])]


# 9. Set Operations

### select the unique elements from an array

In [154]:
arr = np.array([1,1,2,2,3,3,4,5,6])
print(np.unique(arr))

[1 2 3 4 5 6]


In [157]:
np.unique(arr).size

6

In [153]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


### compute the intersection & union of two arrays

In [154]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [155]:
# intersection
print(np.intersect1d(arr1, arr2))

[3 4 5]


In [156]:
# union
print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


### compute whether each element of an array is contained in another

In [157]:
print(np.in1d(arr1, arr2))

[False False  True  True  True]


In [158]:
arr1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [159]:
arr2

array([[5, 6, 7, 8],
       [5, 6, 7, 8]])

In [161]:
# preserve the shape of the array in the output, if the array is of higher dimensions
print(np.isin(arr1, arr2))

[[False False False False]
 [False False False False]]


In [163]:
arr1 = np.array([1, 2, 3, 4,10, 10, 5])
arr2 = np.array([1, 10])
np.isin(arr1, arr2)

array([ True, False, False, False,  True,  True, False])

### compute the elements in an array that are not in another

In [159]:
print(np.setdiff1d(arr1, arr2))

[1 2]


### compute the elements in either of two arrays, but not both

In [160]:
print(np.setxor1d(arr1, arr2))

[1 2 6 7]


# 10. Linear Algebra

In [161]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)

### matrix multiplication

In [162]:
print(arr1.dot(arr2))
# or
print(np.dot(arr1, arr2))
# or
print(arr1 @ arr2)

[[2.51623511 2.86218675 2.46149074 2.04223873 1.68511463]
 [0.97887139 1.12545821 1.08799709 0.91490076 0.71161775]
 [1.76553731 2.31931894 1.70683443 1.69936475 1.24178866]
 [1.16873119 1.51462574 1.20311322 1.18600669 0.82424827]
 [1.15498347 1.31753805 1.11707168 0.8826558  0.70418125]]
[[2.51623511 2.86218675 2.46149074 2.04223873 1.68511463]
 [0.97887139 1.12545821 1.08799709 0.91490076 0.71161775]
 [1.76553731 2.31931894 1.70683443 1.69936475 1.24178866]
 [1.16873119 1.51462574 1.20311322 1.18600669 0.82424827]
 [1.15498347 1.31753805 1.11707168 0.8826558  0.70418125]]
[[2.51623511 2.86218675 2.46149074 2.04223873 1.68511463]
 [0.97887139 1.12545821 1.08799709 0.91490076 0.71161775]
 [1.76553731 2.31931894 1.70683443 1.69936475 1.24178866]
 [1.16873119 1.51462574 1.20311322 1.18600669 0.82424827]
 [1.15498347 1.31753805 1.11707168 0.8826558  0.70418125]]


### QR factorization 

In [163]:
arr = np.random.rand(5,5)

q, r = np.linalg.qr(arr)
print(q)
print(r)

[[-0.4432654   0.32513554  0.61941338 -0.50166373  0.24992646]
 [-0.53313979 -0.84083639  0.01631061 -0.07809998 -0.04889265]
 [-0.497832    0.2725315   0.2186724   0.71963447 -0.33496042]
 [-0.00757871  0.09648464 -0.05319421 -0.440347   -0.89100964]
 [-0.52094492  0.32202228 -0.75194002 -0.17451256  0.17043949]]
[[-1.71197975 -1.721771   -0.91763767 -1.14596917 -1.48828016]
 [ 0.          0.18511396  0.15670431 -0.3105988  -0.02561779]
 [ 0.          0.         -0.56886488  0.09863229 -0.28981768]
 [ 0.          0.          0.         -0.31671114 -0.28469988]
 [ 0.          0.          0.          0.         -0.67088305]]


### singular value decomposition (SVD)

In [164]:
arr = np.random.rand(5,5)

u, s, v = np.linalg.svd(arr)
print(u)
print(s)
print(v)

[[-0.31707494  0.50745837  0.27489595 -0.52708908 -0.53717669]
 [-0.467027   -0.43107604  0.5391023  -0.31541122  0.4538102 ]
 [-0.53255432  0.56212351 -0.33998784  0.16799359  0.50654662]
 [-0.34108705  0.00379167  0.4323183   0.76786776 -0.32729992]
 [-0.53046657 -0.49057337 -0.57559542 -0.06964278 -0.37654055]]
[2.83737775 0.69055824 0.47487856 0.23943839 0.10871122]
[[-0.42059018 -0.38307359 -0.21951733 -0.6476369  -0.45687757]
 [-0.63976954  0.71850762 -0.25227551  0.00271298  0.10388191]
 [ 0.20378291  0.23608185 -0.1886435   0.38886392 -0.84613023]
 [-0.40137463 -0.52295215 -0.41054126  0.61598638  0.13204589]
 [ 0.45953212  0.08824872 -0.82706633 -0.22339365  0.21702294]]


### compute eigen values

In [165]:
arr = np.random.rand(5,5)
print(np.linalg.eigvals(arr))

[ 2.85678022 -0.67311818  0.37430308  0.1524331  -0.07643027]


### eigen value decomposition

In [166]:
arr = np.random.rand(5,5)

w, v = np.linalg.eig(arr)
print(w)    # eigen values
print(v)    # eigen vectors

[ 2.76395772+0.j          0.10174612+0.23654886j  0.10174612-0.23654886j
 -0.52935513+0.05320233j -0.52935513-0.05320233j]
[[ 0.27758037+0.j         -0.55997738+0.j         -0.55997738-0.j
   0.22379469-0.00692696j  0.22379469+0.00692696j]
 [ 0.45939229+0.j          0.17076292+0.34885444j  0.17076292-0.34885444j
  -0.70496349+0.j         -0.70496349-0.j        ]
 [ 0.48172485+0.j          0.21554976-0.3991528j   0.21554976+0.3991528j
   0.0228234 -0.0005529j   0.0228234 +0.0005529j ]
 [ 0.48237473+0.j          0.37310246-0.2373618j   0.37310246+0.2373618j
   0.12243854-0.18721414j  0.12243854+0.18721414j]
 [ 0.49715556+0.j         -0.28133211+0.23470715j -0.28133211-0.23470715j
   0.60718075+0.18347867j  0.60718075-0.18347867j]]


### compute the trace & determinant

In [167]:
# notice this is not a function in linalg!!!
print(np.trace(arr))    

1.9087397083691204


In [168]:
print(np.linalg.det(arr))

0.05187451362412393


### calculate the inverse/psedo-inverse of a matrix

In [169]:
arr = np.random.rand(5,5)

In [170]:
# compute the inverse of a matrix
print(np.linalg.inv(arr))

[[  2.37704915  -2.18278595  14.14976233 -17.3879446   -4.13238747]
 [ -2.65572368   2.85561316   6.39432678 -11.58940717   1.15627517]
 [ -0.64187733   2.8106897   11.3550277  -20.17896096  -0.58449384]
 [  4.52924162  -5.63978854  -0.64934041   4.47682269  -1.75308404]
 [ -2.16914098   1.49607223 -25.1450202   37.98516176   4.2574866 ]]


In [171]:
# compute the psudo-inverse of a matrix
print(np.linalg.pinv(arr))

[[  2.37704915  -2.18278595  14.14976233 -17.3879446   -4.13238747]
 [ -2.65572368   2.85561316   6.39432678 -11.58940717   1.15627517]
 [ -0.64187733   2.8106897   11.3550277  -20.17896096  -0.58449384]
 [  4.52924162  -5.63978854  -0.64934041   4.47682269  -1.75308404]
 [ -2.16914098   1.49607223 -25.1450202   37.98516176   4.2574866 ]]


### solve a linear system

In [172]:
# solve a linear system in closed form
y = [1,2,3,4,5]
print(np.linalg.solve(arr, y))

[-49.75295153 -18.33776982 -44.59372785   0.44351389  98.61602289]


In [173]:
# calculate the least-squares solution of a linear system
y = [1,2,3,4,5]
solution, residuals, rank, singular = np.linalg.lstsq(arr, y)
print(solution)
print(residuals)
print(rank)
print(singular)

[-49.75295153 -18.33776982 -44.59372785   0.44351389  98.61602289]
[]
5
[2.21809418 0.85765544 0.52823685 0.09333081 0.0173482 ]


C:\Users\igumn\AppData\Local\Temp\ipykernel_15340\727852024.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  solution, residuals, rank, singular = np.linalg.lstsq(arr, y)
